title: "Distributed Cafe"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"

show_downloads: false

markdown: GFM

exclude:
  - documentation.md

mermaid:
  theme: "default"
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.2"