name: Publish Docker image

on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy:
    strategy:
      matrix:
        directory: ['WarehouseService', 'menu-service', 'orders-service', 'server', 'manager-application', 'customer-application']
    env:
      REPO: distributedcafe/${{ matrix.directory }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: WarehouseService shadowJar
        if: ${{ matrix.directory == 'WarehouseService' }}
        run: |
          chmod +x gradlew
          ./gradlew :WarehouseService:shadowJar

      - name: To lower case
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.REPO }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/${{ matrix.directory }}
          push: true
          tags: ${{ steps.string.outputs.lowercase }}